# Essential, reviewed baseline for a clean Mac rebuild.
# Add optional software only after it has earned a place in the baseline.
brew "ansible"
brew "direnv"
brew "gh"
brew "git"
brew "go"
brew "mas"
brew "node"
brew "python@3.13"
brew "ripgrep"
brew "terraform"
brew "uv"
brew "wget"
brew "yq"

cask "adobe-acrobat-reader"
cask "caffeine"
cask "chatgpt"
cask "claude"
cask "codex"
cask "duet"
cask "flux-app"
cask "gcloud-cli"
cask "google-chrome"
cask "logi-options-plus"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "obsidian"
cask "spotify"
cask "tailscale-app"
cask "typora"
cask "visual-studio-code"
cask "whatsapp"
cask "wechat"
cask "wispr-flow"
cask "zoom"

vscode "openai.chatgpt"
npm "@anthropic-ai/claude-code"
